name:                simple-graphql-client
version:             1.0.0.0
github:              "Pixura/simple-graphql-client"
license:             MIT
author:              "Charles Crain"
maintainer:          "charles@superrare.com"
copyright:           "Pixura"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Pixura/simple-graphql-client#readme>

dependencies:
- base >= 4.7 && < 5
- wreq
- http-client-tls
- http-client
- http-types
- text
- aeson
- lens
- exceptions

library:
  source-dirs: src

tests:
  simple-graphql-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-graphql-client
    - file-embed
